const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p/w780";

const posterPathById: Record<string, string> = {
  "eyes-wakanda-s1": "/yuOfb1MgnaGPa4guzV0n1IFYVGN.jpg",
  "captain-first-avenger": "/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
  "agent-carter-one-shot": "/4vFKKWPvCVDJTOWiwReBfpAMScP.jpg",
  "agent-carter-s1": "/fe79VYyLp5ZBstpJ4oukpuUT3B.jpg",
  "agent-carter-s2": "/fe79VYyLp5ZBstpJ4oukpuUT3B.jpg",
  "fantastic-four-first-steps": "/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg",
  "captain-marvel": "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
  "iron-man": "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
  "iron-man-2": "/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
  "funny-thing-thor-hammer": "/ugrdgmZlSuiavH0NFurhlUPIRD0.jpg",
  "incredible-hulk": "/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
  thor: "/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
  "the-consultant": "/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
  avengers: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
  "item-47": "/hnSxG8clwLuAXEkp9emc8HCUcHD.jpg",
  "aos-s1": "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
  "thor-dark-world": "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
  "iron-man-3": "/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
  "all-hail-the-king": "/y0QYZPWgeGKOvyrzi6Oz3aJPxJa.jpg",
  "winter-soldier": "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
  "aos-s2": "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
  guardians: "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "guardians-2": "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
  "i-am-groot-s1": "/3QfQYECgu6DX5UUWCBvv1Fl0BAJ.jpg",
  "i-am-groot-s2": "/3QfQYECgu6DX5UUWCBvv1Fl0BAJ.jpg",
  "daredevil-s1": "/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
  "jessica-jones-s1": "/oxnWofiE9fHOgUfs9NJa6nG6NTR.jpg",
  "age-of-ultron": "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
  "whih-s1": "/2RAbC1bwYvE3kYr6PdYFUo6vmO6.jpg",
  "ant-man": "/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
  "aos-s3": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  "daredevil-s2": "/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
  "luke-cage-s1": "/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
  "iron-fist-s1": "/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
  "defenders-s1": "/49XzINhH4LFsgz7cx6TOPcHUJUL.jpg",
  "civil-war": "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
  "black-widow": "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
  "black-panther": "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  homecoming: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
  "team-thor": "/hpHvGuMc46pppwpcW0Xk7eys3L4.jpg",
  "team-thor-2": "/2jmP71A5Un0jDNqBesDPQSN8hjJ.jpg",
  "punisher-s1": "/tM6xqRKXoloH9UchaJEyyRE9O1w.jpg",
  "doctor-strange": "/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
  "aos-slingshot": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  "aos-s4": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  "jessica-jones-s2": "/oxnWofiE9fHOgUfs9NJa6nG6NTR.jpg",
  "luke-cage-s2": "/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
  "iron-fist-s2": "/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
  "daredevil-s3": "/Af0nAOjCdeZ2I9g9134GQNNQRuH.jpg",
  "aos-s5": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  ragnarok: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
  "team-darryl": "/edroTAeTEM9ILyAnumA0ALxRSne.jpg",
  "punisher-s2": "/jgfYU0zWySnyapKIv6bTq2QHgH1.jpg",
  "jessica-jones-s3": "/oxnWofiE9fHOgUfs9NJa6nG6NTR.jpg",
  "inhumans-s1": "/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg",
  "runaways-s1": "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
  "cloak-dagger-s1": "/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
  "runaways-s2": "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
  "cloak-dagger-s2": "/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
  "runaways-s3": "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
  "ant-man-wasp": "/cFQEO687n1K6umXbInzocxcnAQz.jpg",
  "infinity-war": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "aos-s6": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  "aos-s7": "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
  "helstrom-s1": "/5QmcKsepYpO9XYsWNLwsiULoaAu.jpg",
  endgame: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
  "loki-s1": "/rX1wQMTKFqF0gvZyS0DDQqgnQPB.jpg",
  "loki-s2": "/rX1wQMTKFqF0gvZyS0DDQqgnQPB.jpg",
  "what-if-s1": "/zaqfFDUrSfIljdD0OBxSjcutX8n.jpg",
  "what-if-s2": "/a87nXpE9vz8AE7qOxy0oaulEIpW.jpg",
  "what-if-s3": "/qGM0WutoTPNmac0IL3Bx7hAeyrk.jpg",
  "friendly-spider-s1": "/kjcsNeqF52YUQ2rUBGLMHwLkxvR.jpg",
  "marvel-zombies-s1": "/mwKj9ERGFXsWot0nXgQ5yMQf9I7.jpg",
  "wandavision-s1": "/ijWWwINc8h71NQ8j1LTJMFSj5wr.jpg",
  "shang-chi": "/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg",
  "falcon-winter-soldier-s1": "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
  "far-from-home": "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
  "peters-to-do-list": "/9OOhqOVo37DQnQ6OUPz0Qlek5Uv.jpg",
  eternals: "/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
  "no-way-home": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
  "multiverse-madness": "/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
  "hawkeye-s1": "/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
  "moon-knight-s1": "/x6FsYvt33846IQnDSFxla9j0RX8.jpg",
  "wakanda-forever": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
  "echo-s1": "/vFyJH630cF68LohVYjQW49074Sy.jpg",
  "she-hulk-s1": "/5xz2orV8f0usyrfGNshcoXHmiaV.jpg",
  "ms-marvel-s1": "/3HWWh92kZbD7odwJX7nKmXNZsYo.jpg",
  "love-thunder": "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
  "ironheart-s1": "/dOh6MJpdlQhYpLBhzhNQeYGKTZ5C.jpg",
  "werewolf-night": "/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
  "guardians-holiday": "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
  quantumania: "/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
  "guardians-3": "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
  "secret-invasion-s1": "/3rINdUPSy9AklJg74jWHOyUXuZd.jpg",
  "the-marvels": "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
  "deadpool-wolverine": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
  "agatha-s1": "/mGsxKwXUjojitRv2E9qMTbxbBRd.jpg",
  "daredevil-ba-s1": "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
  "brave-new-world": "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
  thunderbolts: "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
  "wonder-man-s1": "/6yy9nQlFt2l6UVWzrfhszFCaZ5C.jpg",
  "punisher-one-last-kill": "/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg",
  "daredevil-ba-s2": "/pXr32DqmkiEJTQbpf9u6JRgPPzB.jpg",
  "brand-new-day": "/iPOn6DinuVyLY17YM9mKuPofV08.jpg",
  "visionquest-s1": "/6j60tGRAjBmWRPTOEwhW6oRbPMP.jpg",
  "avengers-doomsday": "/cWXtJhrlruF8CeYuaBGE8vdj3Q9.jpg",
  "avengers-secret-wars": "/f0YBuh4hyiAheXhh4JnJWoKi9g5.jpg",
  "xmen-first-class": "/hNEokmUke0dazoBhttFN0o3L7Xv.jpg",
  "xmen-origins-wolverine": "/yj8LbTju1p7CUJg7US2unSBk33s.jpg",
  xmen: "/vF02RqXLgtmpJM5CRLSuvN3fVHi.jpg",
  x2: "/bst4alFUXCxISwdRUKSMhhkrX1M.jpg",
  "xmen-last-stand": "/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg",
  "the-wolverine": "/t2wVAcoRlKvEIVSbiYDb8d0QqqS.jpg",
  "days-future-past": "/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
  "xmen-apocalypse": "/ikA8UhYdTGpqbatFa93nIf6noSr.jpg",
  "dark-phoenix": "/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
  deadpool: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
  "new-mutants": "/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg",
  "deadpool-2": "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
  logan: "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
  "xmen-tas-s1": "/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg",
  "xmen-tas-s2": "/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg",
  "xmen-tas-s3": "/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg",
  "xmen-tas-s4": "/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg",
  "xmen-tas-s5": "/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg",
  "xmen-97-s1": "/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg",
  "xmen-97-s2": "/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg",
  "legion-s1": "/xhJtYVTsdXQCIlB5hAXkMCPUG9y.jpg",
  "legion-s2": "/xhJtYVTsdXQCIlB5hAXkMCPUG9y.jpg",
  "legion-s3": "/xhJtYVTsdXQCIlB5hAXkMCPUG9y.jpg",
  "gifted-s1": "/nshCqszjTNuqhrB53vrSqWO18sE.jpg",
  "gifted-s2": "/sHeE3FSbRlw1GX8U6GMKLuiUmph.jpg",
  "pryde-xmen": "/hM5e3Pw2xdY3SKtFXbUqPlPJI3T.jpg",
  "xmen-evolution-s1": "/At5aZIKkN8zHTAXOnQR9D3b7usW.jpg",
  "xmen-evolution-s2": "/At5aZIKkN8zHTAXOnQR9D3b7usW.jpg",
  "xmen-evolution-s3": "/At5aZIKkN8zHTAXOnQR9D3b7usW.jpg",
  "xmen-evolution-s4": "/At5aZIKkN8zHTAXOnQR9D3b7usW.jpg",
  "wolverine-xmen-s1": "/oSeJ2nESB77iC6SLo4qcqoadjdt.jpg",
  "xmen-anime-s1": "/j4MRuaMIpbq8jpXt864R9ebzzuS.jpg",
  "wolverine-anime-s1": "/dy8w7wSioNAgAykP91hiSGVgxJJ.jpg",
  "generation-x": "/wqkTCfznNXtYO9UnnxComqhhHRP.jpg",
  "fantastic-four-2005": "/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg",
  "silver-surfer": "/9wRfzTcMyyzkQxVDqBHv8RwuZOv.jpg",
  "fantastic-four-2015": "/cDroz5qSlP8xZ6tOpeYoPkBvKyL.jpg",
  "new-fantastic-four-s1": "/kEyV8MffIg2Zmmaif5GHeiHYHq4.jpg",
  "the-thing-1979-s1": "/eDyeUNRBCIn2GeS4hIM0HT3xDBw.jpg",
  "fantastic-four-1994-s1": "/jPVGruDYZtImosRkNv7eZhqxT1p.jpg",
  "fantastic-four-1994-s2": "/jPVGruDYZtImosRkNv7eZhqxT1p.jpg",
  "silver-surfer-1998-s1": "/18rhdRDXAAHUTsbWtIQn2ZkjRL9.jpg",
  "fantastic-four-wgh-s1": "/zCtCW0JlbMpzfQDAX1bO1o1KLi.jpg",
};

const multiPlatformById: Record<string, string> = {
  homecoming: "Netflix · Disney+ · TV+ · TOD",
  "far-from-home": "Netflix · Disney+ · TOD",
  "no-way-home": "Netflix · Disney+",
  "incredible-hulk": "Apple TV · kirala/satın al",
};

const unavailableInTurkey = new Set([
  "daily-bugle-s1",
  "daily-bugle-s2",
  "generation-x",
  "pryde-xmen",
  "xmen-evolution-s1",
  "xmen-evolution-s2",
  "xmen-evolution-s3",
  "xmen-evolution-s4",
  "wolverine-xmen-s1",
  "xmen-anime-s1",
  "wolverine-anime-s1",
  "fantastic-four-1967-s1",
  "new-fantastic-four-s1",
  "the-thing-1979-s1",
  "fantastic-four-1994-s1",
  "fantastic-four-1994-s2",
  "silver-surfer-1998-s1",
  "fantastic-four-wgh-s1",
]);

export function posterUrlFor(contentId: string) {
  const path = posterPathById[contentId];
  return path ? `${TMDB_IMAGE_BASE}${path}` : null;
}

export function platformFor(contentId: string, availableUnits: number) {
  if (contentId === "fantastic-four-1994-unreleased") return "Yayımlanmadı";
  if (!availableUnits) return "Yakında";
  if (multiPlatformById[contentId]) return multiPlatformById[contentId];
  if (unavailableInTurkey.has(contentId)) return "Türkiye’de yayında değil";
  return "Disney+";
}
